config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  namespace :api do 
    get "/users_email" => "users_email#show", as: :users_email
    
    resources :favorites, only: [:create, :destroy]
  end

  get "/properites/search", to: "properties/search#index"

  resources :properties, only: :show do 
    resources :reservations, only: :new, controller: "properties/reservations"
  end

  resources :reservation_payments, only: :create

  resources :profiles, only: [:show, :update]

  resources :accounts, only: [:show, :update]

  resources :passwords, only: [:show, :update]

  resources :payments, only: :index

  put "/hostify/:user_id", to: "hosts#update", as: :hostify
  
  namespace :host do 
    get "/dashboard", to: "dashboard#index", as: :dashboard

    resources :properties, only: [:new, :create]

    resources :payments, only: :index
  end
end
 

app/models/profile.rb
class Profile < ApplicationRecord
  include Countriable
  
  belongs_to :user
  has_one_attached :picture

  geocoded_by :address
  after_validation :geocode, if: -> { address.present? && latitude.blank? && longitude.blank? }


  def address
    [address_1, address_2, city, state, zip_code, country_name].compact.join(', ')
  end

  def full_name 
    "#{first_name} #{last_name}".squish
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController 
  before_action :authenticate_user!
  before_action :set_profile, only: [:show, :update]
  
  def show 
    authorize @profile
  end

  def update 
    authorize @profile
    @profile.update(profile_params)
    redirect_to profile_path(@profile)
  end

  private 

  def profile_params 
    params.require(:profile).permit(:first_name, :last_name, :address_1, 
                                    :address_2, :city, :zip_code, :country_code, :picture)
  end

  def set_profile 
    @profile = Profile.find(params[:id])
  end
end

app/views/profiles/_sidebar.html.erb
<aside class="py-6 px-2 sm:px-6 lg:py-0 lg:px-0 lg:col-span-3 profile-sidebar">
  <nav class="space-y-1">
    <%= link_to profile_path(current_user.profile), class:"text-gray-900 hover:text-gray-900 hover:bg-gray-50 group rounded-md px-3 py-2 flex items-center text-sm font-medium #{ "active" if controller_name == "profiles" }" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-gray-400 group-hover:text-gray-500 flex-shrink-0 -ml-1 mr-3">
        <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
      </svg>
      <span class="truncate">Profile</span>
    <% end %>

    <%= link_to account_path(current_user), class: "text-gray-900 hover:text-gray-900 hover:bg-gray-50 group rounded-md px-3 py-2 flex items-center text-sm font-medium #{ "active" if controller_name == "accounts" }" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-gray-400 group-hover:text-gray-500 flex-shrink-0 -ml-1 mr-3">
        <path stroke-linecap="round" stroke-linejoin="round" d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.324.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 011.37.49l1.296 2.247a1.125 1.125 0 01-.26 1.431l-1.003.827c-.293.24-.438.613-.431.992a6.759 6.759 0 010 .255c-.007.378.138.75.43.99l1.005.828c.424.35.534.954.26 1.43l-1.298 2.247a1.125 1.125 0 01-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.57 6.57 0 01-.22.128c-.331.183-.581.495-.644.869l-.213 1.28c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.02-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 01-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 01-1.369-.49l-1.297-2.247a1.125 1.125 0 01.26-1.431l1.004-.827c.292-.24.437-.613.43-.992a6.932 6.932 0 010-.255c.007-.378-.138-.75-.43-.99l-1.004-.828a1.125 1.125 0 01-.26-1.43l1.297-2.247a1.125 1.125 0 011.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.087.22-.128.332-.183.582-.495.644-.869l.214-1.281z" />
        <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
      </svg>
      <span class="truncate">Account</span>
    <% end %>

    <%= link_to password_path(current_user),  class: "text-gray-900 hover:text-gray-900 hover:bg-gray-50 group rounded-md px-3 py-2 flex items-center text-sm font-medium #{ "active" if controller_name == "passwords" }" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-gray-400 group-hover:text-gray-500 flex-shrink-0 -ml-1 mr-3">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 5.25a3 3 0 013 3m3 0a6 6 0 01-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1121.75 8.25z" />
      </svg>
      <span class="truncate">Password</span>
    <% end %>

    <%= link_to payments_path(current_user), class: "text-gray-900 hover:text-gray-900 hover:bg-gray-50 group rounded-md px-3 py-2 flex items-center text-sm font-medium #{ "active" if controller_name == "payments" }" do %> 
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-gray-400 group-hover:text-gray-500 flex-shrink-0 -ml-1 mr-3">
        <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 8.25h19.5M2.25 9h19.5m-16.5 5.25h6m-6 2.25h3m-3.75 3h15a2.25 2.25 0 002.25-2.25V6.75A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25v10.5A2.25 2.25 0 004.5 19.5z" />
      </svg>
      <span class="truncate">Reservations &amp; Payments</span>
    <% end %>
  </nav>
</aside>

app/views/profiles/show.html.erb
<div class="h-full bg-gray-100 profiles-page">
  <main class="max-w-7xl mx-auto pb-10 lg:py-12 lg:px-8">
    <div class="lg:grid lg:grid-cols-12 lg:gap-x-5">

    <%= render "profiles/sidebar" %>
    
      <div class="space-y-6 sm:px-6 lg:px-0 lg:col-span-9">
        <section aria-labelledby="payment-details-heading">
          <%= form_with model: @profile, local: true, url: profile_path(@profile) do |f| %>
            <div class="shadow sm:rounded-md sm:overflow-hidden">
              <div class="bg-white py-6 px-4 sm:p-6">
                <div>
                  <h2 id="payment-details-hearing" class="text-lg leading-6 font-medium text-gray-900">Update profile</h2>
                  <p class="mt-1 text-sm text-gray-500">Update your profile information</p>
                </div>

                <div class="mt-6 grid grid-cols-4 gap-6">
                  <div class="col-span-4 sm:col-span-2">
                    <%= f.label :first_name, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :first_name, class: "mt-1 block w-full border border-gray-200 rounded-md shadow-sm py-2 px-3 foucs:outine-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="col-span-4 sm:col-span-2">
                    <%= f.label :last_name, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :last_name, class: "mt-1 block w-full border border-gray-200 rounded-md shadow-sm py-2 px-3 foucs:outine-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="col-span-4">
                    <%= f.label :address_1, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :address_1, class: "mt-1 block w-full border border-gray-200 rounded-md shadow-sm py-2 px-3 foucs:outine-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="col-span-4">
                    <%= f.label :address_2, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :address_2, class: "mt-1 block w-full border border-gray-200 rounded-md shadow-sm py-2 px-3 foucs:outine-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="col-span-4">
                    <%= f.label :city, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :city, class: "mt-1 block w-full border border-gray-200 rounded-md shadow-sm py-2 px-3 foucs:outine-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="cols-span-4 sm:col-span-2">
                    <%= f.label :zip_code, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :zip_code, class: "mt-1 block w-full border border-gray-200 rounded-md shadow-sm py-2 px-3 foucs:outine-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="col-span-4 sm:col-span-2">
                    <%= f.label :country_code, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.country_select :country_code, { priority_countries: ["US", "CA"] }, class: "mt-1 block w-full border border-gray-200 rounded-md shadow-sm py-2 px-3 foucs:outine-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="col-span-4 sm:col-span-2">
                    <%= f.label :picture, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.file_field :picture %>
                  </div>
                </div>
              </div>
              <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                <%= f.submit :save, class: "bg-gray-800 border border-transparent rounded-md shadow-sm text-white p-2 cursor-pointer" %>
              </div>
            </div>
          <% end %>
        </section>
      </div>
    </div>
  </main>
</div>