config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  namespace :api do 
    get "/users_email" => "users_email#show", as: :users_email
    
    resources :favorites, only: [:create, :destroy]
  end

  get "/properites/search", to: "properties/search#index"

  resources :properties, only: :show do 
    resources :reservations, only: :new, controller: "properties/reservations"
  end

  resources :reservation_payments, only: :create

  resources :profiles, only: [:show, :update]

  resources :accounts, only: [:show, :update]

  resources :passwords, only: [:show, :update]

  resources :payments, only: :index

  put "/hostify/:user_id", to: "hosts#update", as: :hostify
  
  namespace :host do 
    get "/dashboard", to: "dashboard#index", as: :dashboard

    resources :properties, only: [:new, :create]

    resources :payments, only: :index
  end
end
 

app/models/property.rb
# frozen_string_literal: true

class Property < ApplicationRecord
  include Countriable

  CLEANING_FEE = 2_000
  CLEANING_FEE_MONEY = Money.new(CLEANING_FEE)
  SERVICE_FEE_PERCENTAGE = 0.09

  validates :name, presence: true
  validates :headline, presence: true
  validates :description, presence: true
  validates :address_1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country_code, presence: true

  belongs_to :user

  has_many_attached :images, dependent: :destroy

  has_many :reviews, as: :reviewable
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :reservations, dependent: :destroy
  has_many :reserved_users, through: :reservations, source: :user
  has_many :payments, through: :reservations

  monetize :price_cents, allow_nil: true

  geocoded_by :address
  after_validation :geocode, if: -> { latitude.blank? && longitude.blank? }

  scope :city, ->(city) { where('lower(city) like ?', "%#{city.downcase}%") }
  scope :country_code, ->(country_code) { where('lower(country_code) like ?', "%#{country_code.downcase}%") }

  scope :between_dates, lambda { |checkin, checkout|
    joins(:reservations)
      .where.not('reservations.checkin_date < ?', Date.strptime(checkin, Date::DATE_FORMATS[:reservation_format]))
      .where.not('reservations.checkout_date > ?', Date.strptime(checkout, Date::DATE_FORMATS[:reservation_format]))
  }

  def address
    # [address_1, address_2, city, state, country].compact.join(', ') faker addresses are not real
    [state, country_name].compact.join(', ')
  end

  def default_image
    images.first
  end

  def favorited_by?(user)
    return if user.nil?

    favorited_users.include?(user)
  end

  def available_dates
    date_format = '%b %e'
    next_reservation = reservations.future_reservations.order(checkout_date: :desc).first

    return Date.tomorrow.strftime(date_format)..Date.today.end_of_year.strftime(date_format) if next_reservation.nil?

    next_reservation.checkout_date.strftime(date_format)..Date.today.end_of_year.strftime(date_format)
  end
end

app/controllers/host/properties_controller.rb
module Host 
  class PropertiesController < ApplicationController 
    before_action :authenticate_user! 

    def new
      authorize current_user, policy_class: HostPolicy
      @property = Property.new(user: current_user)
    end

    def create 
      authorize current_user, policy_class: HostPolicy
      @property = current_user.properties.new(property_params)

      if @property.save 
        redirect_to host_dashboard_path 
      else
        render :new
      end
    end 

    private 

    def property_params
      params.require(:property).permit(:name, :description, :headline, :address_1, :address_2, :city, :state, :zip_code, :country_code)
    end
  end
end

app/controllers/properties/reservations_controller.rb
# frozen_string_literal: true

module Properties
  class ReservationsController < ApplicationController
    before_action :authenticate_user!

    def new
      @property      =  Property.find(params[:property_id])
      @reservation   =  @property.reservations.new
      @checkin_date  =  reservation_params[:checkin_date]
      @checkout_date =  reservation_params[:checkout_date]
      @nightly_total =  reservation_params[:nightly_total]
      @cleaning_fee  =  reservation_params[:cleaning_fee]
      @service_fee   =  reservation_params[:service_fee]
      @total_cost    =  reservation_params[:total_cost]
    end

    private

    def reservation_params
      params.permit(:checkin_date, :checkout_date, :nightly_total,
                    :cleaning_fee, :service_fee, :total_cost)
    end
  end
end

app/controllers/properties/search_controller.rb
module Properties 
  class SearchController < ApplicationController 
    def index 
      @properties = Property.all

      if search_params[:city].present? 
        @properties = @properties.city(search_params[:city])
      end

      if search_params[:country_code].present? 
        @properties = @properties.country_code(search_params[:country_code])
      end

      available_properties = @properties.includes(:reservations).select { |property| property.reservations.size.zero? }
      
      if search_params[:checkin_date] && search_params[:checkout_date] 
        @properties = @properties.between_dates(search_params[:checkin_date], search_params[:checkout_date])
      end
    
      @properties = Property.where(id: available_properties.map(&:id) + @properties.ids )
    end

    private 

    def search_params 
      params.permit(:city, :country_code, :checkin_date, :checkout_date)
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def show 
    @property = Property.find(params[:id])
  end
end

app/views/properties/_product_info.html.erb
<div class="mx-auto max-w-2xl px-4 pt-10 pb-16 sm:px-6 lg:grid lg:max-w-7xl lg:grid-cols-3 lg:grid-rows-[auto,auto,1fr] lg:gap-x-8 lg:px-8 lg:pt-16 lg:pb-24">
  <div class="lg:col-span-2 lg:border-r lg:border-gray-200 lg:pr-8">
    <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">Private room in vacation home hosted by Vakhtang</h1>
  </div>

  <!-- reservations controller -->
  <div
    class="mt-4 lg:mt-0 lg:row-span-3"
    data-controller="reservation"
    data-checkin-date="<%= Date.tomorrow.to_fs(:reservation_format) %>"
    data-checkout-date="<%= (Date.tomorrow + 1.day).to_fs(:reservation_format) %>"
    data-nightly-price="<%= humanized_money(@property.price) %>"
    data-service-fee-percentage="<%= Property::SERVICE_FEE_PERCENTAGE %>"
    data-cleaning-fee="<%= humanized_money(Property::CLEANING_FEE_MONEY) %>"
    >
    <div class="mt-10 lg:mt-0">
      <div class="bg-white">
        <h3 class="text-2xl font-medium text-gray-900"><%= humanized_money_with_symbol(@property.price) %> night</h3>

        <div class="isolate -space-y-px rounded-md shadow-sm mt-6 flex items-center border-2 border-black box-border">
          <div class="relative border border-black rounded-md w-full rounded-b-none px-3 py-2 focus-within:z-10 focush-within:ring-1 focus-within:ring-black focus-within:border-black">
            <label 
              for="name" 
              class="bloc text-xs font-medium text-gray-900 uppercase">
              Check-in
            </label>
            <input 
              type="text" 
              name="name" 
              id="name" 
              autocomplete="off"
              class="block w-full border-0 p-o text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm" 
              placeholder="11/30/2022"
              data-reservation-target="checkin"
              >
          </div>
          <div class="relative border border-black rounded-md w-full rounded-b-none px-3 py-2 focus-within:z-10 focush-within:ring-1 focus-within:ring-black focus-within:border-black">
            <label 
              for="name" 
              class="bloc text-xs font-medium text-gray-900 uppercase">
              Checkout
            </label>
            <input 
              type="text" 
              name="name"
              id="name" 
              autocomplete="off"
              class="block w-full border-0 p-o text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm" 
              placeholder="12/7/2022"
              data-reservation-target="checkout"
              >
          </div>
        </div>

        <div class="divide-y divide-gray-200">
        </div>
        <dl class="space-y-6 mt-6">
          <div class="flex items-center justify-between">
            <dt class="text-sm"><%= humanized_money_with_symbol(@property.price ) %> x <span data-reservation-target="numberOfNights">0</span></dt>
            <dd class="text-sm font-medium text-gray-900">$<span data-reservation-target="nigtlyTotal">0.00</span></dd>
          </div>
          <div class="flex items-center justify-between">
            <dt class="text-sm">Cleaning fee</dt>
            <dd class="text-sm font-medium text-gray-900"><%= humanized_money_with_symbol(Property::CLEANING_FEE_MONEY) %></dd>
          </div>
          <div class="flex items-center justify-between">
            <dt class="text-sm">Service fee</dt>
            <dd class="text-sm font-medium text-gray-900">$<span data-reservation-target="serviceFee" >0.00</span></dd>
          </div>
          <div class="flex items-center justify-between border-t border-gray-200 pt-6">
            <dt class="text-sm">Total</dt>
            <dd class="text-sm font-medium text-gray-900">$<span data-reservation-target="totalCost">0.00</span></dd>
          </div>
        </dl>

        <div class="pt-6">
          <button 
            type="submit" 
            class="w-full airbnb-pinkish-gradient border border-transparent rounded-md shadow-sm py-3 px-4 text-base font-medium text-white"
            data-submit-url="<%= new_property_reservation_path(@property) %>"
            data-action="reservation#submitReservation"
            >
            Confirm Order
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="py-10 lg:col-span-2 lg:col-start-1 lg:border-r lg:border-gray-200 lg:pt-6 lg:pb-16 lg:pr-8">
    <!-- Description and details -->
    <div>
      <h3 class="font-bold">Description</h3>

      <div class="space-y-6">
        <p class="text-base text-gray-900"><%= truncate @property.description, length: 500 %></p>
        <% if @property.description.length > 500 %>
          <%= link_to "Show more >", "", class: "text-lg font-medium underline", data: { action: "property#readDescription" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/modal", modal_trigger_id: "property-description-trigger", modal_content: "properties/property_description", content_params: { property: @property } %>

app/views/properties/_property.html.erb
<%= link_to property_path(property) do %>
  <li 
    class="relative"
    data-geolocation-target="property"
    data-google-maps-target="property"
    data-latitude="<%= property.latitude %>"
    data-longitude="<%= property.longitude %>"
    >
    <div class="group block w-full aspect-w-10 aspect-h-7 rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-offest-gray-100 focus:ring-indigo-500 overflow-hidden">
      <%= image_tag property.default_image, class: "object-cover pointer-events-none group-hover:opacity-75" %>
      <button type="button" class="absolute inset-0 focus:outline-none">
        <span class="sr-only">View Details</span>
      </button>

      <div class="flex flex-row-reverse p-2">
        <svg 
          xmlns="http://www.w3.org/2000/svg" 
          viewBox="0 0 24 24" 
          stroke-width="1.5" 
          stroke="black" 
          class="w-7 h-7 cursor-pointer"
          data-controller="favorites"
          data-action="click->favorites#mark"
          data-logged-in-user="<%= user_signed_in? %>"
          data-user-id="<%= current_user&.id %>"
          data-property-id="<%= property.id %>"
          data-favorite-id="<%= property.favorites.find_by(user: current_user)&.id %>"
          data-marked="<%= property.favorited_by?(current_user) %>"
          data-marked-color="red"
          data-unmarked-color="#ced4da"
          fill="<%= property.favorited_by?(current_user) ? "red" : "#ced4da" %>" 
          >
          <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
        </svg>
      </div>
    </div>
    <p class="mt-2 block text-sm font-medium text-gray-900 truncate pointer-event-none">
      <%= property.city %>, <%= property.state %>, <%= property.country_name %>
    </p>
    <p data-distance class="block text-sm font-medium text-gray-500 truncate pointer-event-none"></p>
    <p class="block text-sm font-medium text-gray-500 truncate pointer-event-none text-black">
      <%= property.average_rating.round(2) %> 
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4 inline-block relative bottom-0.5">
        <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd" />
      </svg>
    </p>
    <p class="block text-black text-sm font-medium text-gray-500 truncate pointer-event-none"><%= property.available_dates.first %> - <%= property.available_dates.last%> </p> 
    <p class="block text-sm font-medium text-gray-500 truncate pointer-event-none">
      <span class="text-black">
        <%= humanized_money_with_symbol(property.price) %> per night
      </span>
    </p>
  </li>
<% end %>

app/views/properties/_property_description.html.erb
<div class="p-4">
  <div class="flex mb-4">
    <div 
      class="flex-none cursor-pointer"
      data-modal-target="closeButton"
      >
      <svg 
        xmlns="http://www.w3.org/2000/svg" 
        fill="none" 
        viewBox="0 0 24 24" 
        stroke-width="1.5" 
        stroke="currentColor" 
        class="w-6 h-6 float-left">
          <path 
          stroke-linecap="round" 
          stroke-linejoin="round" 
          d="M6 18L18 6M6 6l12 12" />
      </svg>
    </div>
  </div>

  <div>
    <p class="text-2xl font-medium mb-4">About this space</p>

    <div>
      <%= content_params[:property].description %>
    </div>
  </div>
</div>

app/views/properties/_reviews.html.erb
<div class="bg-white">
  <div class="max-w-2xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8 lg:grid lg:grid-cols-12 lg:gap-x-8">
    <div class="lg:col-span-4">
      <h2 class="text-2xl font-extrabold tracking-tight text-gray-900">Custom Reviews</h2>
      <div class="mt-3 flex items-center">
        <div>
          <div class="flex items-center">    
            <% property_star_classes = ["text-gray-300", "text-gray-300", "text-gray-300", "text-gray-300", "text-gray-300"]

              @property.average_rating.round(0).times do |i|
                property_star_classes[i] = "text-yellow-400"
              end
            %>

            <% property_star_classes.each do |star_class| %>
              <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink-0 h-5 w-5 <%= star_class %>" viewBox="0 0 20 20" fill="currentColor">
                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
              </svg>
            <% end %>
          </div>
          <p class="sr-only"><%= @property.average_rating.round(0) %> out of 5 stars</p>
        </div>
        <p class="ml-2 text-sm text-gray-900">Based on <%= @property.reviews_count%> revies</p>
      </div>

      <div class="mt-6">
        <h3 class="sr-only">Review data</h3>

        <div class="space-y-3">
          <% 5.downto(1) do |n| %>
            <div class="flex items-center text-sm">
              <dt class="flex-1 flex items-center">
                <p class="w-3 font-medium text-gray-900"><%= n %><span class="sr-only">star reviews</span></p>
                <div aria-hidden="true" class="ml-1 flex-1 flex items-center">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill text-yellow-400" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                  </svg>

                  <div class="ml-3 relative flex-1">
                    <div class="h-3 bg-gray-100 border border-gray-200 rounded-full"></div>
                    <div style="width: calc(<%= @property.reviews.where(rating: n).size %> /  <%= @property.reviews_count %> * 100%)" class="absolute inset-y-0 bg-yellow-400 border border-yellow-400 rounded-full"></div>
                  </div>
                </div>
              </dt>
              <dd class="ml-3 w-10 text-right tabular-nums text-sm text-gray-900"><%= property_average_rating_percntage(property: @property, rating: n) %>%</dd>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="mt-16 lg:mt-0 lg:col-start-6 lg:col-span-7">
      <h3 class="sr-only">Recent reviews</h3>
      <div class="flow-root">
        <div class="-my-12 divide-y divide-gray-200">
          <% @property.reviews.includes(user: :profile).limit(6).each do |review| %>
            <div class="py-12">
              <div class="flex items-center">
                <%= image_tag review.user.profile.picture, class: "h-12 w-12 rounded-full" , alt: review.user.full_name %>
                <div class=" ml-2">
                  <h4 class="text-sm font-bold text-gray-900"><%= review.user.full_name %></h4>
                  <div class="mt-1 flex items-center">
                    <% review_star_classes = ["text-gray-300", "text-gray-300", "text-gray-300", "text-gray-300", "text-gray-300"]

                      review.rating.times do |i|
                        review_star_classes[i] = "text-yellow-400"
                      end
                    %>

                    <% review_star_classes.each do |star_class| %>
                      <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink-0 h-5 w-5 <%= star_class %>" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                      </svg>
                    <% end %>
                  </div>
                  <p class="sr-only"><%= review.rating %> out of 5 starts</p>
                </div>
              </div>
              <div class="mt-4 space-y-6 text-base italic text-gray-600">
                <p><%= review.body %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/properties/_search_form.html.erb
<div 
  data-controller="property-search"
  data-checkin-date="<%= (Date.tomorrow).to_fs(:reservation_format) %>"
  data-checkout-date="<%= (Date.tomorrow + 1.day).to_fs(:reservation_format) %>"
  class="p-4"
>
  <div class="flex mb-4">
    <div 
      class="flex-none cursor-pointer"
      data-modal-target="closeButton"
      >
      <svg 
      xmlns="http://www.w3.org/2000/svg" 
        fill="none" 
        viewBox="0 0 24 24" 
        stroke-width="1.5" 
        stroke="currentColor" 
        class="w-6 h-6 float-left">
          <path 
          stroke-linecap="round" 
          stroke-linejoin="round" 
          d="M6 18L18 6M6 6l12 12" />
      </svg>
    </div>
  </div>

  <%= form_with(url: properites_search_path, method: :get, local: true, class: "space-y-8 divide-y divide-gray-200 p-4") do |f| %>
    <div class="space-y-8 divide-y divide-ray-200 sm:space-y-5">
      <div class="space-y-6 sm:space-y-5">
        <div>
          <h3 class="text-lg leading-6 font-medium text-gray-900">Search for property</h3>
        </div>
        <div class="space-y-6 sm:space-y-5">
          <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
            <%= f.label :city, class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" %>
            <div class="mt-1 sm:mt-0 sm:col-span-2">
              <%= f.text_field :city, class: "max-w-lg block w-full shadow-sm foucs:ring-indigo-500 sm:max-w-xs sm:text-sm border-gray-300 rounded-md" %>
            </div>
          </div>

          <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
            <%= f.label :country_code, "Country", class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" %>
            <div class="mt-1 sm:mt-0 sm:col-span-2">
              <%= f.country_select :country_code, { priority_countries: ["US", "CA"] }, class: "max-w-lg block w-full shadow-sm foucs:ring-indigo-500 sm:max-w-xs sm:text-sm border-gray-300 rounded-md" %>
            </div>
          </div>

          <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
            <%= f.label :checkin_date, "Check in", class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" %>
            <div class="mt-1 sm:mt-0 sm:col-span-2">
              <%= f.text_field :checkin_date, class: "max-w-lg block w-full shadow-sm foucs:ring-indigo-500 sm:max-w-xs sm:text-sm border-gray-300 rounded-md", data: { "property-search-target": "checkin" }, required: true %>
            </div>
          </div>

          <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
            <%= f.label :checkout_date, "Check out", class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" %>
            <div class="mt-1 sm:mt-0 sm:col-span-2">
              <%= f.text_field :checkout_date, class: "max-w-lg block w-full shadow-sm foucs:ring-indigo-500 sm:max-w-xs sm:text-sm border-gray-300 rounded-md",  data: { "property-search-target": "checkout" }, required: true %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="pt-5">
      <div class="flex justify-end">
        <%= f.submit "Search", class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-white airbnb-pinkish-gradient rounded-md cursor-pointer focus:ring-2 focus:ring-offset-2 focust:ring-indigo-500 mr-10" %>
      </div>
    </div>
  <% end %>
</div>